/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    vehicles: Vehicle;
    models: Model;
    specials: Special;
    reviews: Review;
    staff: Staff;
    leads: Lead;
    'trade-in-photos': TradeInPhoto;
    media: Media;
    users: User;
    'preview-visits': PreviewVisit;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    specials: SpecialsSelect<false> | SpecialsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'trade-in-photos': TradeInPhotosSelect<false> | TradeInPhotosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'preview-visits': PreviewVisitsSelect<false> | PreviewVisitsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    dealer: Dealer;
  };
  globalsSelect: {
    dealer: DealerSelect<false> | DealerSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cars for sale. Set the status to Sold to take a car off the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  /**
   * Built automatically from year, model and variant.
   */
  title?: string | null;
  model: number | Model;
  /**
   * e.g. 1.5T Luxury
   */
  variant: string;
  year: number;
  mileage: number;
  condition: 'new' | 'demo' | 'used';
  price: number;
  body: 'SUV' | 'Electric' | 'Bakkie' | 'Sedan';
  fuel: 'Petrol' | 'Diesel' | 'Electric' | 'REEV';
  transmission: string;
  stockNumber?: string | null;
  colour: string;
  /**
   * #RRGGBB, used to tint the stock card.
   */
  colourHex?: string | null;
  /**
   * The first photo is the card image. A transparent side-profile cut-out looks best.
   */
  photos: (number | Media)[];
  description?: string | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  status: 'available' | 'reserved' | 'sold';
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The new-vehicle range. These drive the home page hero and range sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  name: string;
  /**
   * Web address part. Leave blank to fill automatically.
   */
  slug?: string | null;
  /**
   * One line, shown under the name.
   */
  tagline: string;
  /**
   * e.g. SUV, Bakkie, Sedan
   */
  type: string;
  /**
   * e.g. Petrol, Electric, Diesel · REEV
   */
  fuel: string;
  /**
   * Lower shows first
   */
  order?: number | null;
  fromPrice: number;
  /**
   * e.g. From R4 999 p/m*
   */
  monthlyFrom?: string | null;
  specs?:
    | {
        /**
         * e.g. 138
         */
        value: string;
        /**
         * e.g. kW
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Side-profile car on a transparent background, facing left.
   */
  cutout: number | Media;
  /**
   * Wide lifestyle photo (about 2.2:1). Used by the glass-slat hero and the range.
   */
  world: number | Media;
  /**
   * Tall version for phones (about 2:3).
   */
  portrait: number | Media;
  interior?: (number | null) | Media;
  colours?:
    | {
        name: string;
        /**
         * #RRGGBB
         */
        hex: string;
        cutout?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  showInHero?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the photo shows, for example: 2026 Uni-S in Putty Grey, side view.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specials".
 */
export interface Special {
  id: number;
  title: string;
  model?: (number | null) | Model;
  /**
   * e.g. From R4 999 p/m
   */
  headline: string;
  details?: string | null;
  image?: (number | null) | Media;
  validUntil?: string | null;
  terms?: string | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  quote: string;
  name: string;
  suburb?: string | null;
  rating: number;
  source?: ('google' | 'facebook' | 'hellopeter' | 'direct') | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  phone?: string | null;
  email?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Enquiries from the website. Update the status as you follow up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type: 'test-drive' | 'finance' | 'trade-in' | 'vehicle' | 'contact';
  status: 'new' | 'contacted' | 'won' | 'lost';
  name: string;
  phone: string;
  email?: string | null;
  /**
   * Model or vehicle the person asked about.
   */
  interest?: string | null;
  vehicle?: (number | null) | Vehicle;
  preferredDate?: string | null;
  message?: string | null;
  /**
   * Extra form answers (finance figures, trade-in details).
   */
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Agreed to be contacted (POPIA).
   */
  consent: boolean;
  /**
   * Photos the customer uploaded with a trade-in request.
   */
  photos?: (number | TradeInPhoto)[] | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-in-photos".
 */
export interface TradeInPhoto {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'sales';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Each time someone opens a private preview link.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preview-visits".
 */
export interface PreviewVisit {
  id: number;
  viewer: string;
  code: string;
  ip?: string | null;
  device?: string | null;
  outcome?: ('granted' | 'refused' | 'expired') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'models';
        value: number | Model;
      } | null)
    | ({
        relationTo: 'specials';
        value: number | Special;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'trade-in-photos';
        value: number | TradeInPhoto;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'preview-visits';
        value: number | PreviewVisit;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  title?: T;
  model?: T;
  variant?: T;
  year?: T;
  mileage?: T;
  condition?: T;
  price?: T;
  body?: T;
  fuel?: T;
  transmission?: T;
  stockNumber?: T;
  colour?: T;
  colourHex?: T;
  photos?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  slug?: T;
  status?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  type?: T;
  fuel?: T;
  order?: T;
  fromPrice?: T;
  monthlyFrom?: T;
  specs?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  cutout?: T;
  world?: T;
  portrait?: T;
  interior?: T;
  colours?:
    | T
    | {
        name?: T;
        hex?: T;
        cutout?: T;
        id?: T;
      };
  published?: T;
  showInHero?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specials_select".
 */
export interface SpecialsSelect<T extends boolean = true> {
  title?: T;
  model?: T;
  headline?: T;
  details?: T;
  image?: T;
  validUntil?: T;
  terms?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  suburb?: T;
  rating?: T;
  source?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  phone?: T;
  email?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  name?: T;
  phone?: T;
  email?: T;
  interest?: T;
  vehicle?: T;
  preferredDate?: T;
  message?: T;
  details?: T;
  consent?: T;
  photos?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-in-photos_select".
 */
export interface TradeInPhotosSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preview-visits_select".
 */
export interface PreviewVisitsSelect<T extends boolean = true> {
  viewer?: T;
  code?: T;
  ip?: T;
  device?: T;
  outcome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer".
 */
export interface Dealer {
  id: number;
  name: string;
  street: string;
  suburb: string;
  city: string;
  postalCode?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  phone: string;
  email: string;
  /**
   * International format, digits only, e.g. 27821234567. Leave blank to hide WhatsApp.
   */
  whatsapp?: string | null;
  hours?:
    | {
        days: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  departments?:
    | {
        name: string;
        phone?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    tiktok?: string | null;
  };
  financeDefaults?: {
    rate?: number | null;
    deposit?: number | null;
    term?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer_select".
 */
export interface DealerSelect<T extends boolean = true> {
  name?: T;
  street?: T;
  suburb?: T;
  city?: T;
  postalCode?: T;
  latitude?: T;
  longitude?: T;
  phone?: T;
  email?: T;
  whatsapp?: T;
  hours?:
    | T
    | {
        days?: T;
        time?: T;
        id?: T;
      };
  departments?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        tiktok?: T;
      };
  financeDefaults?:
    | T
    | {
        rate?: T;
        deposit?: T;
        term?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}